d <- read.csv("~/Desktop/weight.csv")
d <- data.frame(as.Date(d$Date, format="%m/%d/%Y"), d$Weight)
colnames(d) <- c("Date", "Weight")
dateTicks <- seq(from = d$Date[1], to = tail(d$Date, n=1), length.out=5)
svg(filename="~/Desktop/weight.svg", height=4, width=20, pointsize=35)
par(mar=c(3, 5, 1, 0), oma=c(0,0,0,0))
plot(d, frame=F, font.main = 1, main="", type="n", yaxt='n', xaxt="n", xlab="", ylab="Weight", col='#333333')
quans <- quantile(d$Weight, names=FALSE)
imean <- round(mean(d$Weight), digits=2)
axis(side=2, at=c(min(d$Weight), max(d$Weight)), lwd="0", lwd.ticks="0", las=1, labels=c(min(d$Weight)-max(d$Weight),0), hadj=.5)
rug(line=-1, jitter(d$Weight, amount=.1), side=2, ticksize = -.15, col='#aaaaaa')
rect(d$Date[1], quans[2], d$Date[-1], quans[4], border="#eeeeee", col="#eeeeee")
lines(d$Date, rep(imean, times=length(d$Date)), col="#aaaaaa")
lines(d$Date, rep(min(d$Weight), times=length(d$Date)), col="#aaaaaa")
lines(d$Date, rep(max(d$Weight), times=length(d$Date)), col="#aaaaaa")
lines(d$Date, d$Weight, col="#666666", lwd=4)
axis.Date(side=1, at=dateTicks, lwd="0", lwd.ticks="1", format="%d %b", col="#cccccc")
dev.off()

